### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by yejunbin** [liaoherui/GDmicro#1]
python GDmicro.py -i Input_files/CRC_FRA_LOSO.csv -s 10  -d CRC -o GDmicro_new_pipe/CRC_FRA_LOSO

 | Test set results: loss=2.9653 accuracy=0.7895 AUC=0.8257
Epoch: 0150 loss_train: 0.0039 acc_train: 1.0000 loss_val: 2.3250 acc_val: 0.6957 time: 0.0057s AUC_train: 1.0000 AUC_val: 0.8400
 | Test set results: loss=2.9706 accuracy=0.7895 AUC=0.8249
Epoch: 0001 loss_train: 0.8204 acc_train: 0.4976 loss_val: 0.7856 acc_val: 0.4894 time: 0.0068s AUC_train: 0.4594 AUC_val: 0.7065
Traceback (most recent call last):
  File "GDmicro.py", line 1303, in <module>
    sys.exit(main())
  File "GDmicro.py", line 1294, in main
    run(input_fs,eg_fs,eg_fs_norm,meta,disease,out,kneighbor,pre_features,rseed,cvfold,doadpt,insp,fnum,nnum,close_cv,anode,reverse,vnode,uf,bsize,rfi,oin)
  File "GDmicro.py", line 1086, in run
    sid,sname=feature_importance_check(selected, selected_arr, feature_id, bset[0], bset[1], test_idx, features, bset[3],bset[2], rdir, bset[4], classes_dict, tid2name, o3, wwl, ot, dcs, fnum, close_cv,o4,eg_fs_norm)
  File "GDmicro.py", line 497, in feature_importance_check
    test_auc=test(model,test_idx,features_tem,adj,labels,ot,max_test_auc,rdir,fn+1,classes_dict,tid2name,0)
TypeError: test() missing 1 required positional argument: 'oin'

**Comment by liaoherui** [comment]
Hi, thanks for using GDmicro!

Sorry for the late reply. I will check it tomorrow and try to solve it asap.

**Comment by liaoherui** [comment]
Hi,

I've fixed the bug and successfully tested the program. Feel free to give it a try. If you encounter any other issues, please inform me.
