### ISSUE TITLE
Can I use GDmicro for multi-classes?

### ISSUE THREAD

**Issue by sskoldas** [liaoherui/GDmicro#2]
Hello,

I haven't tried it yet, but I'm curious about using GDmicro for multi-class classification. Is it compatible for multi-class classification? Or was it developed only for binary classification?

Best!

**Comment by liaoherui** [comment]
Hi, Seda!

Currently, GDmicro was developed for binary classification. If you want to classify multi-label of one test sample, one potential solution is to run models built for different diseases respectively.

**Comment by sskoldas** [comment]
Thank you for the quick response! 
I have a microbiome dataset for one disease but the disease has different clinical conditions. I want to classify these clinical conditions and find biomarkers. 
What do you mean by "run models built for different diseases respectively"? Are you suggesting that I run the model for each class label, i.e. label it as "one versus all"?

**Comment by liaoherui** [comment]
Hi, in your case, you can try the model for each condition (as the binary classification). For example, sample A has three disease conditions: c1 (1), c2(0), c3 (1), similarly, sample B could have: c1 (0), c2 (1), c3 (1), and so on.

Then you can build models for c1, c2, c3, respectively. As a result, there are three models: m1, m2, and m3.

Then, you can run these models for test samples:
m1 -> predict: c1: 0 or 1
m2 -> predict: c2: 0 or 1
……

Not sure whether this operation can meet your requirement. Let me know if I have a misunderstanding about your requirement or you have any other problems when using GDmicro.
