### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by gwcde** [liaoherui/GDmicro#3]
![676b7bc1eb23aa52d51bb07a9cdcaa4](https://github.com/liaoherui/GDmicro/assets/61725013/a56d5fc6-7aab-4ae4-a4e6-cc9e1e053e0c)

python GDmicro.py -i Input_files/CRC_10fold.csv -t 1  -d CRC -o GDmicro_new_pipe/CRC_10fold
There was an error running CRC dataset directly, and no modifications were made before execution.

**Comment by liaoherui** [comment]
Hi, thanks for using GDmicro!

The log shows that "Rscript" is not found. Have you installed all required packages with the conda command? (please see "Install" section of the README page)

**Comment by gwcde** [comment]
Thank you, now it runs successfully. In running 10-fold cross-validation, I found that the Area Under the Curve (AUC) result of each fold is determined by selecting the best AUC result from 150 epochs. 
![d6e270099398bedbaefeef74db6c6fc](https://github.com/liaoherui/GDmicro/assets/61725013/8364d0dd-a7da-44cb-b6fb-684c1e962e7a)

**Comment by liaoherui** [comment]
In practical applications, GDmicro strives to identify robust and accurate microbial markers that can effectively distinguish between case and control samples. Consequently, the program has been updated to implement the model with the highest performance, ensuring satisfactory results for this task.
